### ISSUE TITLE
submission ID

### ISSUE THREAD

**Issue by touristourist** [mdenna-synaptics/codalab2022#1]
Hello, I have some problems. First, the link https://codalab.lisn.upsaclay.fr/my/competition/1755/submissions/ is 404.  And how to find our submission ID? Thanks!

**Comment by mdenna-synaptics** [comment]
I added username, filename and submission date to each entry in the report.

Thanks,
Maurizio


On Jul 12, 2022, at 09:44, touristourist ***@***.******@***.***>> wrote:

CAUTION: Email originated externally, do not click links or open attachments unless you recognize the sender and know the content is safe.



Hello, I have some problems. First, the link https://codalab.lisn.upsaclay.fr/my/competition/1755/submissions/<https://urldefense.proofpoint.com/v2/url?u=https-3A__codalab.lisn.upsaclay.fr_my_competition_1755_submissions_&d=DwMCaQ&c=7dfBJ8cXbWjhc0BhImu8wVIoUFmBzj1s88r8EGyM0UY&r=Vk691SHrqPMn0gZSgjKCFIPOPvlSV8Hh5VXr0RsWBi4&m=mrO5EMSzHsYAgPXeObYzlALH7W8T-Zoh78iG5kqI4q1SBf8lJAG7TJPGgZiEjE5v&s=cyiFjRZX6KMQaTZKAO5bV1IrE8B_dIWcPFMwkK9cgp4&e=> is 404. And how to find our submission ID? Thanks!
