### ISSUE TITLE
Can a team submit with multiple accounts?

### ISSUE THREAD

**Issue by CCjiahao** [mdenna-synaptics/codalab2022#7]
I found that some teams used multiple accounts to submit, I personally feel that it is not harmful, but when the final ranking is calculated, is it calculated according to one team or multiple teams?
If I have method A and method B, and I think both methods are ok, can I submit both methods separately using two accounts?

---

Another question: is it allowed to use additional datasets for training?

**Comment by mdenna-synaptics** [comment]
Hi, for details regarding the competition rules and schedule please contact Andrey directly (see contact details on the competition home page).
I’m mainly taking care of the onboard inference

Thanks
