### ISSUE TITLE
output_size not equal 1

### ISSUE THREAD

**Issue by CCjiahao** [mdenna-synaptics/codalab2022#8]
```python
output_details = interpreter.get_output_details()
output_size, output_zero_point = output_details[0]['quantization']
##### output_size != 1
# This led to me having to get real out by zooming, as follows:
out_true = out * output_size
```
The out_scale of the tflite model I derived from is not equal to 1, whether this has an impact at the final stage.

**Comment by 2019zhou** [comment]
@mdenna-synaptics

**Comment by mdenna-synaptics** [comment]
If you can avoid this additional rescale of the output it would be better, in any case it will not work well if the output itself is quantized to 8 bits
