### ISSUE TITLE
about output rescale

### ISSUE THREAD

**Issue by CCjiahao** [mdenna-synaptics/codalab2022#9]
I asked you about output rescale before, thank you very much for your answer, but I still have a little question:
In the final stage, when you verify the accuracy of the model, will you help us implement the logic of this rescale?
Because I have to weigh whether to solve the problem of rescale, after all, it will consume a certain amount of inference time.

**Comment by mdenna-synaptics** [comment]
I will not be involved in the final stage verification, that will be done by some automatic script put in place by ETHZ.
Honestly I don't think they will consider making special cases.
In any case don't forget that the final stage will evaluate uint8 models. Applying the rescale to uint8 values is not a good idea in my opinion, if the scale is >1 you will risk overflow/saturation, if it is < 1 you will lose details

**Comment by CCjiahao** [comment]
thank you very much! I decided not to take the risk. Solve this rescale problem.
